---
title: "Линейная регрессия: все, что вы занали, но успели забыть"
format: revealjs
---

## Введение

* Статистика: о чем это вообще

* Регрессия
    - Регрессия в ML
    - Регрессия в статистике
      

## План

1. Парная линейная регрессия

2. Множественная линейная регрессия

3. Типичные проблемы

4. Нелинейные предикторы
   
   


## Необходимые библиотеки

```{python}
#| echo: true
import pandas as pd
import numpy as np

import seaborn as sns

import statsmodels.api as sm
import statsmodels.formula.api as smf
```

PS При составлении примеров ни один подрядчик не пострадал.

## 1. Парная линейная регрессия

Пример: зависимость стоимости перевозок от веса посылки.

$X$ - вес груза.

$Y$ - стоимость перевозок, выставленная подрядчиком.

Подозрение: менеджер по логистике "дружит" с неким перевозчиком и проводит счета по завышенным ставкам.


## Разведочный анализ

```{python}
data = pd.read_csv('data/regression/example1.csv')
sns.scatterplot(data=data, x='x', y='Y', style='suspect')
# sns.scatterplot(data=data, x='x', y='Y', style='speed')
```


## 1.1. Понятие линейной регрессии

Уравнение

## 1.2. Метод наименьших квадратов


## 1.3. Диагностика

## 1.4. Так что же там с ценой перевозок?
Подрядчик заточен на "скоропорт", у него есть гарантия скорости доставки и в договоре прописаны штрафы.


## 2. Множественная линейная регрессия

Пример: прогноз сроков доставки и скрытые задержки.

$x_1$, - расстояние, $x_2$ - сезон, $x_3$ - тип груза.

$Y$ - срок доставки.

Отдел доставки выставляет "средние" сроки, но некоторые перевозчики систематически задерживают грузы, списывая на "плохую погоду", хотя у другие успевают.
